repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "^.*migrations.*$"
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: 84b06bb89750b5b557057508fcc294d8af7a469b
    hooks:
      - id: pylint
        additional_dependencies:
          - . # <-- that makes it install current project
        args: ["--disable=C0301,C0114,C0115,C0116,E0401,R0902,W1201,W1203,W0511,R1735,R0903"]